/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddFriendSearch: typeof import('./components/AddFriendSearch.vue')['default']
    ApplyNotification: typeof import('./components/Notification/ApplyNotification.vue')['default']
    ChatMessage: typeof import('./components/ChatMessage/index.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FileMessage: typeof import('./components/ChatMessage/FileMessage.vue')['default']
    GroupBase: typeof import('./components/GroupBase.vue')['default']
    ImageMessage: typeof import('./components/ChatMessage/ImageMessage.vue')['default']
    LoginInput: typeof import('./components/LoginInput.vue')['default']
    LoginSelect: typeof import('./components/LoginSelect.vue')['default']
    LoginSelectOption: typeof import('./components/LoginSelectOption.vue')['default']
    NavMenu: typeof import('./components/NavMenu.vue')['default']
    NotSupportedMessage: typeof import('./components/ChatMessage/NotSupportedMessage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SessionItem: typeof import('./components/SessionItem.vue')['default']
    SplashScreen: typeof import('./components/SplashScreen.vue')['default']
    SplitterPanel: typeof import('./components/SplitterPanel.vue')['default']
    TextMessage: typeof import('./components/ChatMessage/TextMessage.vue')['default']
    UserBase: typeof import('./components/UserBase.vue')['default']
    UserItem: typeof import('./components/UserItem.vue')['default']
    VideoMessage: typeof import('./components/ChatMessage/VideoMessage.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
