/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ChatMessage: typeof import('./components/ChatMessage/index.vue')['default']
    copy: typeof import('./components/LoginInput copy.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    FileMessage: typeof import('./components/ChatMessage/FileMessage.vue')['default']
    ImageMessage: typeof import('./components/ChatMessage/ImageMessage.vue')['default']
    LoginInput: typeof import('./components/LoginInput.vue')['default']
    LoginSelect: typeof import('./components/LoginSelect.vue')['default']
    LoginSelectItem: typeof import('./components/LoginSelectItem.vue')['default']
    LoginSelectOption: typeof import('./components/LoginSelectOption.vue')['default']
    NavMenu: typeof import('./components/NavMenu.vue')['default']
    NoSupperdMessage: typeof import('./components/ChatMessage/NoSupperdMessage.vue')['default']
    NotSuppdMessage: typeof import('./components/ChatMessage/NotSuppdMessage.vue')['default']
    NotSupportdMessage: typeof import('./components/ChatMessage/NotSupportdMessage.vue')['default']
    NotSupportedMessage: typeof import('./components/ChatMessage/NotSupportedMessage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SessionItem: typeof import('./components/SessionItem.vue')['default']
    TextMessage: typeof import('./components/ChatMessage/TextMessage.vue')['default']
    VideoMessage: typeof import('./components/ChatMessage/VideoMessage.vue')['default']
  }
}
